### ISSUE TITLE
CSS Dimensions

### ISSUE THREAD

**Issue by ulivz** [ulivz/javascript-fragment#2]
# Introduction

若一个元素的style如下：

```css
{
            height: 300px;
            width: 200px;
            margin: 10px;
            border: 10px solid #ddd;
            padding: 10px;
}
```

那么：

- 通过 jQuery获取：
```
width() = 200
height() = 300

innerWidth() = 220
innerHeight() = 320

outerWidth() = 240
outerHeight() = 340
```

- 原生方法获取：
```
offsetHeight = 340
offsetWidth = 240

scrollWidth = 220
scrollHeight = 1020

clientHeight = 320
clientWidth = 220 
```

对应关系：

jQuery | Native | 备注
---|---|---
width() | 无 | 
innerWidth() | clientWidth | 
outerWidth() | offsetWidth |
